config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', :as => :rails_health_check

  root 'pages#home'
  get 'about' => 'pages#about'

  resources :articles do
    collection do
      get 'trashed', action: :list_trashed
    end

    member do
      patch 'restore'
    end

    resources :comments, only: %i[create destroy]
  end

  resources :categories, only: %i[index show new edit create update]

  get 'signup' => 'users#new'
  resources :users, except: :new

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/article.rb
class Article < ApplicationRecord
  include Discard::Model

  belongs_to :author, class_name: 'User', inverse_of: :articles, counter_cache: true

  has_many :comments, -> { order(created_at: :desc) }, inverse_of: :article, dependent: :destroy

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates :title, presence: true, length: 6..100
  validates :description, presence: true, length: 10..300

  scope :published, -> { where(published_at: ..Time.current) }

  def draft?
    !published_at
  end

  def published?
    published_at && published_at <= Time.current
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include Pagy::Backend

  before_action :require_login, only: %i[new edit create update destroy restore list_trashed]
  before_action :set_article, only: %i[show edit update destroy restore]
  before_action :authorize, only: %i[edit update destroy restore]

  def index
    @pagy, @articles = pagy(
      Article.preload(:author, :categories)
             .kept
             .published
             .order(published_at: :desc)
    )
  end

  def show
    if @article.discarded? || !@article.published?
      require_login and return
      authorize and return
    end

    @pagy, @comments = pagy(@article.comments.preload(:author))
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params) do |a|
      a.author_id = current_user.id
    end

    if @article.save
      redirect_to @article, notice: 'Article created'
    else
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article updated'
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @article.discard || @article.destroy!

    flash.notice = 'Article moved to trash' if @article.persisted?
    redirect_to current_user, status: :see_other
  end

  def restore
    @article.undiscard!
    redirect_to current_user, notice: 'Article restored'
  end

  def list_trashed
    articles = current_user.articles
                           .preload(:author, :categories)
                           .discarded
                           .order(discarded_at: :desc)

    @pagy, @articles = pagy(
      current_user.admin? ? articles.unscope(where: :author_id) : articles
    )
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :published_at, category_ids: [])
  end

  def authorize
    return if @article.author_id == current_user.id || current_user.admin?

    redirect_back_or_to root_path, alert: 'Unauthorized'
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  include Pagy::Frontend

  def can_infer_author?
    controller_name == 'users' && action_name == 'show'
  end
end

app/views/articles/_article.html.erb
<tr>
  <td><%= article.title %></td>

  <% unless can_infer_author? %>
    <td><%= article.author.username %></td>
  <% end %>

  <td><%= render 'categories/joined', categories: article.categories %></td>
  <td>
    <% if article.draft? %>
      Draft
    <% elsif article.published? %>
      <%= time_ago_in_words(article.published_at) %> ago
    <% else %>
      Scheduled
    <% end %>
  </td>

  <td><%= link_to 'View', article %></td>

  <% authorized = logged_in? && (article.author_id == current_user.id || current_user.admin?) %>
  <% if authorized && article.discarded? %>
    <td><%= link_to 'Restore', restore_article_path(article), data: { turbo_method: :patch } %></td>
    <td>
      <%= link_to 'Delete forever', article, data: {
        turbo_method: :delete,
        turbo_confirm: %(Delete "#{article.title}" forever? You won't be able to restore it.)
      } %>
    </td>
  <% else %>
    <td><%= link_to_if authorized, 'Edit', edit_article_path(article) %></td>
    <td>
      <%= link_to_if authorized, 'Move to trash', article, data: { turbo_method: :delete } %>
    </td>
  <% end %>
</tr>

app/views/articles/_form.html.erb
<%= form_with model: @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label "#{:categories} (select zero or more)" %><br>
    <%= f.collection_select :category_ids, Category.all, :id, :name, multiple: true, size: 3 %>
  </p>
  <p>
    <%= f.label 'Publish date (leave it blank to save as a draft)' %><br>
    <% if @article.new_record? %>
      <%= f.datetime_select :published_at, include_blank: true, selected: Time.current %>
    <% else %>
      <%= f.datetime_select :published_at, include_blank: true %>
    <% end %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/_table.html.erb
<% if @articles.any? %>
  <% unless controller_name == 'articles' %>
    <h2>Articles</h2>
  <% end %>

  <table>
    <thead>
    <tr>
      <th>Title</th>

      <% unless can_infer_author? %>
        <th>Author</th>
      <% end %>

      <th>Categories</th>
      <th>Publish date</th>
      <th colspan='3'>Actions</th>
    </tr>
    </thead>
    <tbody>
    <%= render @articles %>
    </tbody>
  </table>

  <%== pagy_nav(@pagy) %>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'shared/errors', obj: @article %>
<%= render 'form' %>

<%= render 'shared/back' %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<%= render 'table' %>

app/views/articles/list_trashed.html.erb
<h1>Articles in trash</h1>

<%= render 'table' %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'shared/errors', obj: @article %>
<%= render 'form' %>

<%= render 'shared/back' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.description %></p>

<hr>

<p>Authored by <%= link_to @article.author.username, @article.author %></p>
<% if @article.categories.any? %>
  <p>Categories: <%= render 'categories/joined', categories: @article.categories %></p>
<% end %>
<p>Publish date: <%= @article.published_at || 'saved as a draft' %></p>
<p>
  Created <%= time_ago_in_words(@article.created_at) %> ago,
  edited <%= time_ago_in_words(@article.updated_at) %> ago
</p>

<% if logged_in? && (@article.author_id == current_user.id || current_user.admin?) %>
  <p>
    <%= link_to 'Edit', edit_article_path(@article) %> |
    <%= link_to 'Delete', @article, data: {
      turbo_method: :delete,
      turbo_confirm: 'Are you sure you want to delete this article?'
    } %>
  </p>
<% end %>

<hr>

<% if @comments.any? %>
  <%= render @comments %>
  <%== pagy_nav(@pagy) %>
<% end %>

<% if logged_in? %>
  <%= render 'comments/form' %>
<% end %>