config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', :as => :rails_health_check

  root 'pages#home'
  get 'about' => 'pages#about'

  resources :articles do
    collection do
      get 'trashed', action: :list_trashed
    end

    member do
      patch 'restore'
    end

    resources :comments, only: %i[create destroy]
  end

  resources :categories, only: %i[index show new edit create update]

  get 'signup' => 'users#new'
  resources :users, except: :new

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, inverse_of: :author, dependent: :destroy
  has_many :comments, inverse_of: :author, dependent: :destroy

  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: 3..25
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { maximum: 105 },
            format: URI::MailTo::EMAIL_REGEXP

  has_secure_password

  before_save :downcase_email

  def admin?
    is_admin?
  end

  private

  def downcase_email
    # `email'         -- Calls `User#email'.
    # `self.email'    -- Calls `User#email'.
    # `email ='       -- Initializes a local variable.
    # `self.email = ' -- Calls `User#email='.
    self.email = email.downcase
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pagy::Backend

  before_action :require_login, only: %i[edit update]
  before_action :set_user, only: %i[show edit update destroy]
  before_action :authorize, only: %i[edit update destroy]

  def index
    @pagy, @users = pagy(User.all)
  end

  def show
    articles = @user.articles.preload(:categories).kept

    @pagy, @articles = pagy(
      if logged_in? && (@user == current_user || current_user.admin?)
        # Drafts come first, scheduled articles second, and published articles last.
        articles.order(Article.arel_table[:published_at].desc.nulls_first)
      else
        articles.published.order(published_at: :desc)
      end
    )
  end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user,
                  notice:
                    "Welcome to the Alpha Blog, #{@user.username}. You've successfully signed up."
    else
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Account information updated'
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @user.destroy!

    # Administrator who deletes other user's account will remain logged in.
    session[:user_id] = nil if @user == current_user
    redirect_to root_path, notice: 'Account deleted'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def authorize
    return if @user == current_user || (current_user.admin? && action_name == 'destroy')

    redirect_to @user, alert: "Cannot edit or delete other users' profiles"
  end
end

app/helpers/users_helper.rb
module UsersHelper
  include Pagy::Frontend
end

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/_user.html.erb
<tr>
  <td><%= user.username %></td>
  <td><%= user.email %></td>
  <td><%= time_ago_in_words(user.created_at) %> ago</td>
  <td><%= user.articles_count %></td>
  <td><%= link_to 'View', user %></td>
  <td><%= link_to_if logged_in? && user == current_user, 'Edit', edit_user_path(user) %></td>
</tr>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'shared/errors', obj: @user %>
<%= render 'form' %>

<%= render 'shared/back' %>

app/views/users/index.html.erb
<h1>Bloggers</h1>

<% if @users.any? %>
  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Date joined</th>
      <th>Articles count</th>
      <th colspan='2'>Profile</th>
    </tr>
    </thead>
    <tbody>
    <%= render @users %>
    </tbody>
  </table>

  <%== pagy_nav(@pagy) %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'shared/errors', obj: @user %>
<%= render 'form' %>

<%= render 'shared/back' %>

app/views/users/show.html.erb
<h1><%= @user.username %>'s profile</h1>

<%= render 'articles/table' %>

<% if logged_in? && (@user == current_user || current_user.admin?) %>
  <p>
    <%= link_to 'Trash', trashed_articles_path %> |
    <%= link_to 'Edit profile', edit_user_path(@user) %> |
    <%= link_to 'Delete account', @user, data: {
      turbo_method: :delete,
      turbo_confirm:
        'Are you sure you want to delete this account? All the articles will be deleted as well.'
    } %>
  </p>
<% end %>