config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', :as => :rails_health_check

  root 'pages#home'
  get 'about' => 'pages#about'

  resources :articles do
    collection do
      get 'trashed', action: :list_trashed
    end

    member do
      patch 'restore'
    end

    resources :comments, only: %i[create destroy]
  end

  resources :categories, only: %i[index show new edit create update]

  get 'signup' => 'users#new'
  resources :users, except: :new

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :articles, through: :categorizations

  validates :name, presence: true, uniqueness: true, length: 3..25
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Pagy::Backend

  before_action :require_login, :authorize, only: %i[new edit create update]
  before_action :set_category, only: %i[show edit update]

  def index
    @pagy, @categories = pagy(Category.all)
  end

  def show
    @pagy, @articles = pagy(
      @category.articles
               .preload(:author, :categories)
               .kept
               .published
               .order(published_at: :desc)
    )
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Category created'
    else
      render :new, status: :unprocessable_content
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Category updated'
    else
      render :edit, status: :unprocessable_content
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def authorize
    return if current_user.admin?

    redirect_to categories_path, alert: 'Administrator account required'
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  include Pagy::Frontend
end

app/views/categories/_category.html.erb
<li>
  <%= link_to category.name, category %> (<%= pluralize(category.articles_count, 'article') %>)
</li>

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
  <p>
    <%= f.label :name, 'Category name' %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/_joined.html.erb
<% *rest, last = categories %>
<% rest.each do |c| %>
  <%= link_to c.name, c %>,
<% end %>
<%= link_to last.name, last if last %>

app/views/categories/edit.html.erb
<h1>Edit category</h1>

<%= render 'shared/errors', obj: @category %>
<%= render 'form' %>

<%= render 'shared/back' %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<% if @categories.any? %>
  <ul>
    <%= render @categories %>
  </ul>

  <%== pagy_nav(@pagy) %>
<% end %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'shared/errors', obj: @category %>
<%= render 'form' %>

<%= render 'shared/back' %>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<%= render 'articles/table' %>

<% if logged_in? && current_user.admin? %>
  <p><%= link_to 'Rename category', edit_category_path(@category) %></p>
<% end %>