config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', :as => :rails_health_check

  root 'pages#home'
  get 'about' => 'pages#about'

  resources :articles do
    collection do
      get 'trashed', action: :list_trashed
    end

    member do
      patch 'restore'
    end

    resources :comments, only: %i[create destroy]
  end

  resources :categories, only: %i[index show new edit create update]

  get 'signup' => 'users#new'
  resources :users, except: :new

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'alert' %>
    <span style='color: red;'><%= msg %></span>
  <% else %>
    <span style='color: green;'><%= msg %></span>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>

    <li>
      <% if logged_in? %>
        <%= link_to 'Create new article', new_article_path %> |
      <% end %>
      <%= link_to 'Articles', articles_path %>
    </li>

    <li>
      <% if logged_in? && current_user.admin? %>
        <%= link_to 'Create new category', new_category_path %> |
      <% end %>
      <%= link_to 'Categories', categories_path %>
    </li>

    <li><%= link_to 'Bloggers', users_path %></li>

    <li>
      <% if logged_in? %>
        <%= link_to "#{current_user.username}#{' (admin)' if current_user.admin?}", current_user %>
        |
        <%= link_to 'Log out', logout_path, data: {
          turbo_method: :delete,
          turbo_confirm: 'Are you sure you want to log out?'
        } %>
      <% else %>
        <%= link_to 'Log in', login_path %> |
        <%= link_to 'Sign up', signup_path %>
      <% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div>
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>